### ISSUE TITLE
Some further docs on HA Matter integration

### ISSUE THREAD

**Issue by quintesse** [Luligu/matterbridge-home-assistant-addon#2]
When I installed the plugin HA also seems to have activated it's default Matter support.
But when I click "Configure" I get the following question that I don't know how to answer:

![image](https://github.com/user-attachments/assets/3c9ff226-46e3-4715-af73-84bb9839c7ba)

Perhaps this could be added to the README with advise on what the correct/best/suggested action is?

**Comment by Luligu** [comment]
Hi,
thanks for your interest.

The correct answer is yes use the official Matter Server add-on.

Just to understand, before you installed the matterbridge-home-assistant-addon, you didn't have Matter Server installed?

And this question pops up as consequence of installing matterbridge-home-assistant-addon?

**Comment by quintesse** [comment]
Hi, indeed, AFAIK I did _not_ have the Matter Server installed, it is in the "Discovered" section. And when I clicked configure it asked me that question. I just accepted it and HA proceeded to install the plugin.

**Comment by Calimerorulez** [comment]
I had the same question like @quintesse. HA installed the Matter integration, but if does not shown any devices:

![image](https://github.com/user-attachments/assets/fb415549-449f-4679-b9f1-bf2fe3869b6e)

In the Matterbridge addons, I've enabled and configured zigbee2mqtt, and Matterbridge sees the devices.
But the aren't shown in the Matter integration. What am I missing?
